# Generated by Django 5.1.15 on 2026-06-08 16:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("recharge", "Rechargement"),
                            ("withdrawal", "Retrait"),
                            ("payment", "Paiement"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("feexpay_mtn", "FeexPay MTN"),
                            ("feexpay_moov", "FeexPay Moov"),
                            ("mtn_direct", "MTN Direct"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours"),
                            ("completed", "Complété"),
                            ("failed", "Échoué"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("external_reference", models.CharField(blank=True, max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction de paiement",
                "verbose_name_plural": "Transactions de paiement",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="payments_pa_user_id_92d873_idx"
                    ),
                    models.Index(
                        fields=["reference"], name="payments_pa_referen_72073c_idx"
                    ),
                    models.Index(
                        fields=["external_reference"],
                        name="payments_pa_externa_e4a306_idx",
                    ),
                ],
            },
        ),
    ]
