# Generated by Django 5.1.15 on 2026-06-10 23:07

from django.db import migrations


def migrate_providers(apps, schema_editor):
    """Migrer les anciens providers vers les nouveaux"""
    PaymentTransaction = apps.get_model('payments', 'PaymentTransaction')
    
    # Mapper les anciens providers vers les nouveaux
    provider_mapping = {
        'feexpay_mtn': 'mtn_momo',
        'feexpay_moov': 'moov_flooz',
        'mtn_direct': 'mtn_momo',
    }
    
    for old_provider, new_provider in provider_mapping.items():
        PaymentTransaction.objects.filter(provider=old_provider).update(provider=new_provider)


def reverse_migrate_providers(apps, schema_editor):
    """Revenir aux anciens providers (rollback)"""
    PaymentTransaction = apps.get_model('payments', 'PaymentTransaction')
    
    # Mapper les nouveaux providers vers les anciens
    provider_mapping = {
        'mtn_momo': 'feexpay_mtn',
        'moov_flooz': 'feexpay_moov',
    }
    
    for new_provider, old_provider in provider_mapping.items():
        PaymentTransaction.objects.filter(provider=new_provider).update(provider=old_provider)


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_add_mtn_momo_fields"),
    ]

    operations = [
        migrations.RunPython(migrate_providers, reverse_migrate_providers),
    ]
